### ISSUE TITLE
Is this still active/relevant?

### ISSUE THREAD

**Issue by Joedang** [psas/launch-tower-comm#40]
I'm going through the list of projects on the PSAS website, making a list of the active/old projects. Is this still a thing? Will this be used with LV3? It hasn't been pushed to in like 2 years.

**Comment by glennl** [comment]
I think Paul is working on this currently.

- Glenn

**Comment by nellump** [comment]
This repo contains the software that runs on the existing launch tower
computer (LTC2), and is definitely still relevant.

**Comment by Joedang** [comment]
Okay, I'll mark this as an active project in the projects list.
